### ISSUE TITLE
Decimal encoding error

### ISSUE THREAD

**Issue by ben-sol** [vekonyz/fast-protocol#3]
/home/ffmuser/node/lib/node_modules/fast-protocol/index.js:1332
         this.encodeI32(ctx, value.e, optional)
                                                  ^
TypeError: Cannot read property 'e' of undefined
    at Encoder.encodeDecimalValue (/home/ffmuser/node/lib/node_modules/fast-protocol/index.js:1332:30)
    at Encoder.encodeGroup (/home/ffmuser/node/lib/node_modules/fast-protocol/index.js:951:11)
    at Encoder.encodeSequence (/home/ffmuser/node/lib/node_modules/fast-protocol/index.js:998:8)
    at Encoder.encodeGroup (/home/ffmuser/node/lib/node_modules/fast-protocol/index.js:970:11)
    at Encoder.encode (/home/ffmuser/node/lib/node_modules/fast-protocol/index.js:916:7)

**Comment by vekonyz** [comment]
optional decimal handling corrected
